### ISSUE TITLE
Raspberrymatic on qemu (Proxmox) non responsive after boot for ~2 minutes

### ISSUE THREAD

**Issue by Rondal** [jens-maus/RaspberryMatic#1205]
**Describe the bug**
After migrating raspberrymatic from a Raspberry Pi 3b to a proxmox virtualization host a strange behavior after boot appears. Migration was done between the same versions. Taking backup from source -> shutdown -> boot new VM -> import backup. At the same time the interface was changed. While taking the backup it was a RPI-RF-MOD on the Raspi. For the VM it is the (same) RPI-RF-MOD on a HB-RF-ETH.

After booting everything seems fine but after clicking Status -> Devices the Webinterface hangs. It will not get responsive again for the next few minutes. After that it is fine again. Reloading the webinterface does not help. CPU usage is not higher than usual during that time. There is one log message that seems out of the ordinary (below). When booting, waiting for that error message and then accessing the said page everything is fine.

So I guess this is a relic of changing from a directly attached RPI-RF-MOD to the same one on a HB-RF-ETH. I'll happily help to debug (even in German language). The only thing I can't do right now is resetting HM devices or starting completly over with the environment due to many of those devices beeing not easily accesible.

**Steps to reproduce the behavior**
1. Have a working configuration on Raspi3 + RPI-RF-MOD
2. Backup & shutdown
3. Install Raspberrymatic on VM (using OVA)
4. Move RPI-RF-MOD to HB-RF-ETH
5. Import backup to VM
6. Reboot
7. Access Webinterface -> Status -> Devices

**Expected behavior**
Just working

**Screenshots**
- Won't show anything, because it just hangs.

**System information:**
 - RaspberryMatic Version: 3.57.4.20210320
 - Used Hardware: Raspi 3b, VM on Proxmox (x64)
 - Used HomeMatic RF-Module: RPI-RF-MOD, HB-RF-ETH (POE)

**Additional context**
Copy & paste from logfile (after that it seems to be fine):
```
Mar 30 14:16:13 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer ERROR [vert.x-worker-thread-3] IO Exception: Could not add interface: HMIP-LEQ0585798
de.eq3.cbcs.legacy.communication.rpc.RpcIOException: java.net.SocketTimeoutException: Read timed out
        at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:110)
        at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94)
        at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82)
        at com.sun.proxy.$Proxy21.newDevices(Unknown Source)
        at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.newDevices(LegacyBackendClient.java:157)
        at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.synchronizedBackendDevices(DeviceUtil.java:222)
        at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:109)
        at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:26)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
        at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
        at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259)
        at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:232)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
        at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:686)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:488)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:106)
        ... 15 more
Mar 30 14:16:13 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer INFO  [vert.x-worker-thread-3] Added InterfaceId: 1009
Mar 30 14:16:13 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer INFO  [vert.x-worker-thread-3] Added InterfaceId: HmIP-RF
Mar 30 14:16:13 de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil INFO  [vert.x-worker-thread-3] updateDevicesForClient HmIP-RF -> 119 device addresses will be added
Mar 30 14:16:13 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer INFO  [vert.x-worker-thread-3] Added InterfaceId: HmIP-RF
Mar 30 14:16:13 de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil INFO  [vert.x-worker-thread-3] updateDevicesForClient HmIP-RF -> 119 device addresses will be added
```

**Comment by jens-maus** [comment]
Sorry, but to me this reads like a latency or runtime communication error between the virtual RaspberryMatic and a HB-RF-ETH. Sorry, but for me this isn't reproducible and until today nobody else has raise a hand that they have the same issue to some extend...
