### ISSUE TITLE
HA addon: Cannot create heating group in WebUI

### ISSUE THREAD

**Issue by jens-maus** [jens-maus/RaspberryMatic#1244]
I installed the `6.0.dev20210415` build and added Raspberrymatic as described in the first post. `HM-MOD-RPI-PCB` integration is working fine and I was able to connect my existing devices.
The problem starts when trying to create a group.

### What I did
- Paired devices and confirmed all of them in the inbox
- Inbox is empty
- Tried to create a group

### What happened
- The modal saying that the group is being created is in an infinite loop
- A XHR POST request to `http://homeassistant.local:8123/pages/jpages/group/save?sid=@srqlB32Qsw@` is getting a 404 answer and therefore fails

### What should happen
- The group is created without an error

I did the configuration according to the first post. My guess is that the POST request should go to  `http://homeassistant.local:8123/e4704d1b_raspberrymatic/pages/jpages/group/save?sid=@srqlB32Qsw@` which is part of the URL containing my installation's hostname. Any pointer on that?

_Originally posted by @lamemate in https://github.com/jens-maus/RaspberryMatic/issues/1087#issuecomment-821843193_

**Comment by Phil7989** [comment]
Hi @jens-maus,

same issue here with 3.65.11.20221218 and one difference. I get no response from /pages/jpages/group/save within 5 minutes. After I reload the page, the group was added with no devices.

My installation: HA Addon with RPI-RF-MOD.

Error on the Logfile
`2022-12-27 08:42:50,601 io.vertx.core.impl.ContextImpl ERROR [vert.x-worker-thread-7] Unhandled exception 
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 17
	at com.google.gson.Gson.fromJson(Gson.java:818) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[HMIPServer.jar:?]
	at de.eq3.ccu.groupadministration.http.service.GroupAdministrationController.save(GroupAdministrationController.java:144) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.GroupRequestWorker.handle(GroupRequestWorker.java:46) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.GroupRequestWorker.handle(GroupRequestWorker.java:10) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_352]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 17
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[HMIPServer.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:465) ~[HMIPServer.jar:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[HMIPServer.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80) ~[HMIPServer.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[HMIPServer.jar:?]
	... 14 more
2022-12-27 08:43:20,516 io.vertx.core.impl.ContextImpl ERROR [vert.x-eventloop-thread-0] Unhandled exception 
java.lang.NullPointerException: null
	at de.eq3.ccu.server.internal.RouteHandler$RequestHandler$1.handle(RouteHandler.java:146) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.RouteHandler$RequestHandler$1.handle(RouteHandler.java:143) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23) ~[HMIPServer.jar:?]
	at io.vertx.core.Promise.fail(Promise.java:89) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.ReplyHandler.doFail(ReplyHandler.java:67) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:76) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:24) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:952) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:919) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:942) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[HMIPServer.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[HMIPServer.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]`

Does that match?

Thank you for your hard work.
