### ISSUE TITLE
Version 3.61.7.20211218: Hoher DutyCycle, WebInterface regaiert nur sporadisch

### ISSUE THREAD

**Issue by mlenz-dmx** [jens-maus/RaspberryMatic#1626]
### Describe the issue you are experiencing

Hallo,
nach dem Update auf Version 3.61.7.20211218 ist der DutyCycle der CCU konstant über 75 (vorher um die 25%) und der DutyCycle des HAP bei 25% (vorherum die 12%).  Scripte werden nicht mehr ausgeführt und im Browser ist es vom Zufall abhängig welche Seiten geöffnet werden können.

Hardware ist die Standard CCU3 von Homematic.
Das Update erfolgte von der Version 3.59.6.20211009.
Das Log ist angehängt. 
[ccu3-webui-2021-12-29.log](https://github.com/jens-maus/RaspberryMatic/files/7787919/ccu3-webui-2021-12-29.log)

### Describe the behavior you expected

Das es nach dem Update so problemlos funktioniert wie zuvor

### Steps to reproduce the issue

1. Update der Firmware auf 3.61.7.20211218 von 3.59.6.20211009

### What is the version this bug report is based on?

3.61.7.20211218 

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
...
Dec 28 23:29:06 ccu3-webui local0.err ReGaHss: ERROR: XMLRPC 'getValue' call failed (interface: 1011, params: {"000A18A9A3CEA2:0","DUTY_CYCLE"}) [CallGetValue():iseXmlRpc.cpp:1435]
Dec 28 23:29:06 ccu3-webui local0.err ReGaHss: ERROR: CallGetValue failed; sVal = 0 [ReadValue():iseDOMdpHSS.cpp:124]
Dec 28 23:29:06 ccu3-webui local0.warn ReGaHss: WARNING: XMLRPC 'getValue': rpcClient.isFault() failed (url: xmlrpc://127.0.0.1:32010, params: {"001098A9963139:1","STATE"}, result: [faultCode:-5,faultString:"Unknown Parameter value for value key: STATE"]) [CallXmlrpcMethod():iseXmlRpc.cpp:2608]
...
Dec 29 08:01:45 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer ERROR [vert.x-worker-thread-3] IO Exception: Could not add interface: 1011 
de.eq3.cbcs.legacy.communication.rpc.RpcIOException: org.apache.http.NoHttpResponseException: 127.0.0.1:31999 failed to respond
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:110)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82)
	at com.sun.proxy.$Proxy21.newDevices(Unknown Source)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.newDevices(LegacyBackendClient.java:157)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.synchronizedBackendDevices(DeviceUtil.java:224)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:109)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:26)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.NoHttpResponseException: 127.0.0.1:31999 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259)
	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:232)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:686)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:488)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:106)
	... 15 more
```

**Comment by jens-maus** [comment]
Tut mir leid, aber ein hoher DutyCycle ist kein Bug von RaspberryMatic, sondern in 99% der Fälle ein Problem in der Programmierung bzw. Gerätelangschaft der eingesetzten HomeMatic/homematicIP Geräte. Auch ist ein Hinweis auf "Vor dem Update lief aber alles" kein Hinweis darauf das ein Problem in der neueren Firmwareversion vorliegt. Daher gehört dies bitte in das entsprechende Nuterforum transferiert (homematic-forum.de oder GitHub Discussions) um dort etwaige Probleme in der Nutzung bzw. lokalen Konfiguration zu suchen und entsprechend auszuschließen.
