### ISSUE TITLE
Raspberrymatic (OCI) erkennt HM-RF-USB-TK nicht

### ISSUE THREAD

**Issue by viKirubanathan** [jens-maus/RaspberryMatic#1767]
### Describe the issue you are experiencing

Wenn ich auf der Homematic Webview auf Geräte anlernen gehe, bekomme ich die Fehlermeldung, dass kein Funkmodul angeschlossen ist.

![image](https://user-images.githubusercontent.com/28481643/158928827-b2536197-a0d6-494a-a516-8be16f6d78ad.png)

### Describe the behavior you expected

Der RF-USB sollte erkannt werden.

### Steps to reproduce the issue

1. Starte meinen Raspberry PI 4b
2. warte 1-2min bis die Docker Container gefahren sind.
3. Gehe auf die Raspberrymatic Seite und klicke auf "Geräte anlernen"

### What is the version this bug report is based on?

ghcr.io/jens-maus/raspberrymatic:latest

### Which base platform are you running?

oci (Open Container Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
/ # vi var/log/boot.log
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Starting logging: OK
Populating /dev using udev: done
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.28.0.2, OK
Identifying Homematic RF-Hardware: .......HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.3, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.3, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.16, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .OK
Starting rfd: .OK
Starting HMIPServer: .....................................................................................................ERROR
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.61.7.20220226 (raspmatic_oci_arm)


hmserver.log
Mar 18 03:48:55 de.eq3.cbcs.server.core.vertx.KeyServerWorker ERROR [vert.x-worker-thread-2] Missing key server configuration parameter (Network.Key) for  mode: KEYSERVER_LOCAL
Mar 18 03:48:58 de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization ERROR [vert.x-eventloop-thread-6] Error 'LOCAL_ADAPTER_NO_SUCH_PORT' while trying to open port '/dev/mmd_hmip':
de.eq3.cbcs.lib.commdevice.CommDeviceException: Exception while trying to open serial port. Check configured port '/dev/mmd_hmip'
        at de.eq3.cbcs.lib.nrjavaserialdevice.SerialCommDevice.open(SerialCommDevice.java:103)
        at de.eq3.cbcs.lib.hmiptrxcommadapter.HomeMaticIPTRXCommAdapter.open(HomeMaticIPTRXCommAdapter.java:894)
        at de.eq3.cbcs.lib.hmiptrxcommadapter.HomeMaticIPTRXCommAdapter.<init>(HomeMaticIPTRXCommAdapter.java:103)
        at de.eq3.cbcs.server.local.base.internal.ShareableHomeMaticIPTRXCommAdapter.<init>(ShareableHomeMaticIPTRXCommAdapter.java:34)
        at de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization.start(LocalServerAdapterInitialization.java:109)
        at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:750)
Caused by: gnu.io.NoSuchPortException
        at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:274)
        at de.eq3.cbcs.lib.nrjavaserialdevice.SerialCommDevice.open(SerialCommDevice.java:95)
        ... 12 more




lighttpdaccess.log

192.168.178.86 192.168.178.51:8080 - [18/Mar/2022:04:02:08 +0100] "POST /esp/system.htm?sid=@kzLnO8j746@&action=UpdateUI HTTP/1.1" 200 1245 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844
192.168.178.86 192.168.178.51:8080 - [18/Mar/2022:04:02:11 +0100] "POST /api/homematic.cgi HTTP/1.1" 200 56 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36"
192.168.178.86 192.168.178.51:8080 - [18/Mar/2022:04:02:11 +0100] "POST /esp/system.htm?sid=@kzLnO8j746@&action=UpdateUI HTTP/1.1" 200 1245 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844
~

lighttpd-error.log

2022-03-18 03:52:02: (gw_backend.c.362) gw-server re-enabled: tcp:127.0.0.1:8183 127.0.0.1 8183
2022-03-18 03:52:02: (gw_backend.c.285) establishing connection failed: socket: tcp:127.0.0.1:8183: Connection refused
2022-03-18 03:52:02: (gw_backend.c.995) all handlers for /esp/system.htm?sid=@OAhO3vgKBB@&action=UpdateUI on  are down.
2022-03-18 03:52:04: (gw_backend.c.362) gw-server re-enabled: tcp:127.0.0.1:8183 127.0.0.1 8183

log/messages
Mar 18 04:02:11 homematic-raspi user.err monit[794]: 'HMIPServer' failed to restart (exit status 1) -- '/etc/init.d/S62HMServer restart': Stopping HMIPServer: OK Starting HMIPServer: ERROR: /dev/mmd_hmip missing
Mar 18 04:02:26 homematic-raspi user.err monit[794]: 'HMIPServer' process is not running
Mar 18 04:02:26 homematic-raspi user.info monit[794]: 'HMIPServer' trying to restart
Mar 18 04:02:26 homematic-raspi user.info monit[794]: 'HMIPServer' restart: '/etc/init.d/S62HMServer restart'
Mar 18 04:02:57 homematic-raspi user.err monit[794]: 'HMIPServer' failed to restart (exit status 1) -- '/etc/init.d/S62HMServer restart': Stopping HMIPServer: OK Starting HMIPServer: ERROR: /dev/mmd_hmip missing
Mar 18 04:03:12 homematic-raspi user.err monit[794]: 'HMIPServer' service restarted 1 times within 1 cycles(s) - exec
Mar 18 04:03:12 homematic-raspi user.err monit[794]: 'HMIPServer' process is not running
Mar 18 04:03:12 homematic-raspi user.info monit[794]: 'HMIPServer' trying to restart
Mar 18 04:03:12 homematic-raspi user.info monit[794]: 'HMIPServer' restart: '/etc/init.d/S62HMServer restart'
```

### Additional information

var/hm_mode

HM_HMIP_ADDRESS='0x1BFD96'
HM_HMIP_ADDRESS_ACTIVE='0xBFEDBC'
HM_HMIP_DEV='HMIP-RFUSB'
HM_HMIP_DEVNODE='/dev/raw-uart1'
HM_HMIP_DEVTYPE='eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.3'
HM_HMIP_SERIAL='1D89B55251'
HM_HMIP_SGTIN='3014F711A000041D89B55251'
HM_HMIP_VERSION='4.4.16'
HM_HMRF_ADDRESS='0xFFF372'
HM_HMRF_ADDRESS_ACTIVE='0xB22CD9'
HM_HMRF_DEV='HMIP-RFUSB'
HM_HMRF_DEVNODE='/dev/raw-uart1'
HM_HMRF_DEVTYPE='eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.3'
HM_HMRF_SERIAL='1D89B55251'
HM_HMRF_VERSION='4.4.16'
HM_HOST='oci'
HM_LED_GREEN=''
HM_LED_GREEN_MODE1='mmc0'
HM_LED_GREEN_MODE2='heartbeat'
HM_LED_RED=''
HM_LED_RED_MODE1='timer'
HM_LED_RED_MODE2='mmc0'
HM_LED_YELLOW=''
HM_LED_YELLOW_MODE1='none'
HM_LED_YELLOW_MODE2='none'
HM_MODE='NORMAL'
HM_RTC=''

Ich habe gestern nach der Anleitung von dieser Seite den Docker Container eingestellt.
https://github.com/jens-maus/RaspberryMatic/wiki/Installation-Docker-OCI

und habe mir diesen RF-USB-Stick besorgt.
https://de.elv.com/elv-homematic-ip-arr-bausatz-rf-usb-stick-fuer-alternative-steuerungsplattformen-hmip-rfusb-fuer-smart-home-hausautomation-152306

**Comment by viKirubanathan** [comment]
habe den container über das deploy.sh erstellt und laufen lassen, anstatt über docker-compose.

**Comment by daxcore** [comment]
ich habe exakt den gleichen Fehler, nur lässt er sich nicht beheben, indem ich das deploy.sh verwendet.

hmserver.log:
```
2023-01-30 19:06:31,848 de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization ERROR [vert.x-eventloop-thread-4] Error 'LOCAL_ADAPTER_NO_SUCH_PORT' while trying to open port '/dev/mmd_hmip': 
de.eq3.cbcs.lib.commdevice.CommDeviceException: Exception while trying to open serial port. Check configured port '/dev/mmd_hmip'
```

```
Starting watchdog...
Identifying host system: oci, OK
Initializing RTC Clock: no hardware found
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Populating /dev using udev: done
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.17.0.2, OK
Identifying Homematic RF-Hardware: ....HmRF: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.4, HmIP: HMIP-RFUSB/eQ-3 HmIP-RFUSB@usb-0000:01:00.0-1.4, OK
Updating Homematic RF-Hardware: HMIP-RFUSB: 4.4.18, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: ...OK
Starting rfd: .OK
Starting HMIPServer: .......................................................................................................................................................ERROR
Starting ReGaHss: .OK
Starting CloudMatic: OK
Starting NeoServer: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.67.10.20230114 (raspmatic_oci_arm)
```

**Comment by jens-maus** [comment]
Dieses Issue/Bugreport ist dicht. hier geht es nicht weiter. Wenn du ähnliche Probleme hast und eine Lösung suchst ist für sowas ein Diskussionsforum gedacht und kein Bugtracker
