### ISSUE TITLE
SSLEngine.closeInbound() error when including device

### ISSUE THREAD

**Issue by maweki** [jens-maus/RaspberryMatic#1773]
### Describe the issue you are experiencing

I am running Raspberrymatic as a home assistant addon. Local inclusion of device works fine. Inclusion via internet doesn't. The handshake works but the key-request to the remote server fails. I include a few log entries (though not all) so that you get the idea that everything seems to work fine until it doesn't.

```
Mar 23 02:10:40 de.eq3.cbcs.server.core.internal.HMIPTRXListener TRACE [RXTXPortMonitor(/dev/raw-uart)] HM /IP Frame received Frametype: HMIP_NM_DEVICE_INCLUSION_REQUEST 
Mar 23 02:10:40 de.eq3.cbcs.server.core.vertx.IncomingHMIPFrameHandler TRACE [vert.x-eventloop-thread-6] AP 3014F5AC9400041D89925F40: HM /IP Frame received  Frametype: HMIP_NM_DEVICE_INCLUSION_REQUEST from 1ACE22 (1ACE22) 
Mar 23 02:10:40 de.eq3.cbcs.server.core.internal.InclusionHandling TRACE [vert.x-eventloop-thread-6] AP 3014F5AC9400041D89925F40: Inclusion Request device with SGTIN: 3014F711A000201A499E72D7; accept Master Key: true; accept Local Key: true 
Mar 23 02:10:40 de.eq3.cbcs.server.core.internal.InclusionHandling TRACE [vert.x-eventloop-thread-6] AP 3014F5AC9400041D89925F40: Device 3014F711A000201A499E72D7 Device description found. Type is DeviceType [label=HmIP-eTRV-B, id=383, manufacturerCode=1, updatable=true, minVersion=0, maxVersion=0] 
Mar 23 02:10:40 de.eq3.cbcs.devicemanagement.util.DeviceAddressingUtil TRACE [vert.x-eventloop-thread-6] AP 3014F5AC9400041D89925F40: Device 3014F711A000201A499E72D7 new assigned address 4A3670 
Mar 23 02:10:40 de.eq3.cbcs.server.core.internal.InclusionHandling TRACE [vert.x-eventloop-thread-6] AP 3014F5AC9400041D89925F40: Added device 3014F711A000201A499E72D7 to device list 
Mar 23 02:10:40 de.eq3.cbcs.server.core.internal.InclusionHandling TRACE [vert.x-eventloop-thread-6] AP 3014F5AC9400041D89925F40: Added device 3014F711A000201A499E72D7 to access point 
Mar 23 02:10:40 de.eq3.cbcs.server.core.persistence.AbstractPersistency TRACE [vert.x-worker-thread-3] DEV 3014F711A000201A499E72D7: Receive persistence command: PERSISTENCE_COMMAND_LOAD_DEVICE_CONFIGURATION 
Mar 23 02:10:40 de.eq3.cbcs.server.core.internal.InclusionHandling DEBUG [vert.x-eventloop-thread-6] AP 3014F5AC9400041D89925F40: Inclusion 3014F711A000201A499E72D7: Step 1 Request handled 1ACE22 (1ACE22) 
Mar 23 02:10:40 de.eq3.cbcs.server.core.vertx.HMIPAbstractWriterWorker TRACE [vert.x-worker-thread-4] AP 3014F5AC9400041D89925F40: Task 10401: Handle message: {"accesspoint.id":"3014F5AC9400041D89925F40","task.id":10401,"command":{"command.type":"HM_GET_INCLUSION_DATA","command.inclusionRequest":"....==","command.newDeviceAddress":"SjZw","command.newBackboneAddress":null,"command.sequenceNumber":100,"command.inclusionKeyMode":"VIA_DEVICE_MASTER_KEY","command.localKey":null}} 
Mar 23 02:10:40 de.eq3.cbcs.server.core.persistence.AbstractPersistency TRACE [vert.x-worker-thread-3] DEV 3014F711A000201A499E72D7: Receive persistence command: PERSISTENCE_COMMAND_ADD_DEVICE 
Mar 23 02:10:40 de.eq3.cbcs.server.core.internal.InclusionHandling DEBUG [RXTXPortMonitor(/dev/raw-uart)] AP 3014F5AC9400041D89925F40: Inclusion 3014F711A000201A499E72D7: Step 2 response from get inclusion data 1ACE22 (1ACE22) -> Router null 
Mar 23 02:10:40 de.eq3.cbcs.server.core.vertx.KeyServerWorker DEBUG [vert.x-worker-thread-2] AP 3014F5AC9400041D89925F40: Inclusion 3014F711A000201A499E72D7: Step 3.0 KeyServerWorker Router null 
Mar 23 02:10:40 de.eq3.cbcs.server.core.transaction.TransactionManagementVerticle TRACE [vert.x-eventloop-thread-5] AP 3014F5AC9400041D89925F40: Task 10401: Processing task response of type TARGET_SUCCESS ...
Mar 23 02:10:40 de.eq3.cbcs.server.core.vertx.keyserver.KeyServerOperation DEBUG [vert.x-worker-thread-2] AP 3014F5AC9400041D89925F40: send data to Frontend Server (jdID 3014F711A000201A499E72D7) at secgtw.homematic.com:8443 
Mar 23 02:10:40 de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler TRACE [vert.x-worker-thread-1] RESPONSE_ACK : {"caller.id":"event","request.id":-1,"notification.type":0,"accesspoint.id":"3014F5AC9400041D89925F40"} 
Mar 23 02:10:40 io.netty.handler.ssl.SslHandler DEBUG [vert.x-eventloop-thread-11] [id: 0x5a6c7f3a, L:/172.30.33.4:33338 - R:secgtw.homematic.com/81.14.202.208:8443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 
Mar 23 02:10:41 de.eq3.cbcs.server.core.vertx.keyserver.KeyServerOperation DEBUG [vert.x-worker-thread-4] AP 3014F5AC9400041D89925F40: received response from Frontend Server (jdID 3014F711A000201A499E72D7) 
Mar 23 02:10:41 de.eq3.cbcs.server.core.vertx.KeyServerWorker DEBUG [vert.x-worker-thread-4] AP 3014F5AC9400041D89925F40: Inclusion 3014F711A000201A499E72D7: Step 3.1 KeyServerWorker response Router null 
```

And then I get

```
Mar 23 02:10:41 io.netty.handler.ssl.SslHandler DEBUG [vert.x-eventloop-thread-11] [id: 0x5a6c7f3a, L:/172.30.33.4:33338 ! R:secgtw.homematic.com/81.14.202.208:8443] SSLEngine.closeInbound() raised an exception. 
javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
	at sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:335)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:291)
	at sun.security.ssl.TransportContext.fatal(TransportContext.java:282)
	at sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:640)
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1355)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:856)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:750)
```

After that

```
Mar 23 02:10:41 de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler TRACE [vert.x-worker-thread-2] DEVICE_INCLUSION_REJECTED : {"caller.id":"event","request.id":-1,"notification.type":57,"accesspoint.id":"3014F5AC9400041D89925F40","device.id":"3014F711A000201A499E72D7"} 
Mar 23 02:10:41 de.eq3.cbcs.server.core.internal.InclusionHandling DEBUG [vert.x-eventloop-thread-2] AP 3014F5AC9400041D89925F40: Device 3014F711A000201A499E72D7 rejected, create transaction for removing 
```

Googling this error basically only shows JDK11 issues with some database connector. I don't really know how to debug any further than this.

### Describe the behavior you expected

Pairing works

### Steps to reproduce the issue

On my installation I just try pairing via the WebUI after factory-resetting the device

### What is the version this bug report is based on?

3.61.7.20220226 (oci)

### Which base platform are you running?

odroid-n2 (ODROID N2/N2+)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
see above
```

**Comment by jens-maus** [comment]
Does this problem still exist because something like that could also be temporar connectivity or server issues...

**Comment by maweki** [comment]
Yes, the issue still exists over multiple reboots and the update to the latest release version.

I tried disabling SSL in the rsFID.conf(? Currently on the train, probably wrong, can't look it up) but apparently the keyserver only accepts secure connections on that port.

I am not sure what's special about my setup. The homematicIP CCU (the always-online app-controlled one) I had before did this key negotiation fine on the same network. Otherwise I have the container within homeassistant OS on the recommended SBC. So it's a setup that should be in use by thousands of people.

**Comment by maweki** [comment]
I still have this issue with the most recent version. Maybe a certificate issue?

**Comment by maweki** [comment]
I would still like to keep that open.

Is there an easy way to maybe change the java version?

**Comment by jens-maus** [comment]
Sorry, but you are defacto the only one with this issue. In addition, what should changing the java version help in this regard? Using Java 8 is the suggested on by the vendor (eQ3)
