### ISSUE TITLE
Installation auf Proxmox funktioniert nicht

### ISSUE THREAD

**Issue by HookHM** [jens-maus/RaspberryMatic#2010]
### Describe the issue you are experiencing

Hallo! Ich wollte die RM auf einem Proxmox installieren und habe die Shell der Proxmox geöffnet und dann 
```wget -qO - https://raspberrymatic.de/install-proxmox.sh | bash -```
eingegeben. Es passiert jedoch nichts, es wird nichts geladen oder sonstiges. 

https://user-images.githubusercontent.com/55434236/197431706-8f628a8b-fbe2-40ac-9d00-39fdd79d5120.mov

Dann habe ich nur die "install-proxmox.sh" geladen und wollte diese Manuell ausführen via ```./install-proxmox.sh``` das funktioniert aber auch nicht wirklich:

```root@proxmox:/home# ./install-proxmox.sh
RaspberryMatic Proxmox installation script V1.4
Copyright (c) 2022 Jens Maus <mail@jens-maus.de>

Getting available RaspberryMatic releases...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd1176170a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/jens-maus/RaspberryMatic/releases (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd1176170a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/jens-maus/RaspberryMatic/releases (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd1176170a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
[ERROR] 1@100 Unknown failure occured.
root@proxmox:/home# ```

### Describe the behavior you expected

*

### Steps to reproduce the issue

1.
2.
3.
...
*

### What is the version this bug report is based on?

3.65.11.20221005

### Which base platform are you running?

ova (Open Virtual Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

n/a

### Anything in the logs that might be useful for us?

```txt
*
```

### Additional information

*

**Comment by jens-maus** [comment]
Welche Proxmox version wird eingesetzt?

**Comment by jens-maus** [comment]
`socket.gaierror: [Errno -3] Temporary failure in name resolution`

Diese Meldung deutet daraufhin das die DNS Einstellungen des Proxmox Host wohl nicht stimmen bzw. der Proxmox Host keinen direkten Zugriff auf das Internet hat. Sieht mir also nach einem lokalen Problem in der Proxmox Installation aus und kein Bug im Install-Skript.

**Comment by HookHM** [comment]
Ja Sorry! Danke für den Hinweis. Der Host hatte noch meinen alten DNS-Server konfiguriert, nun klappt es.
