### ISSUE TITLE
hmipserver constantly failing

### ISSUE THREAD

**Issue by RoadRunnr** [jens-maus/RaspberryMatic#2047]
### Describe the issue you are experiencing

Since upgrading to 3.65.11.20221005, hmipserver is constantly beeing restarted by the watchdog.
It was running normally before the upgrade.

The UI has this in alert message:

   "WatchDog: hmipserver-restart"

### Describe the behavior you expected

no restarts

### Steps to reproduce the issue

Just run it.

### What is the version this bug report is based on?

3.65.11.20221005

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
messages:

Nov 14 11:07:21 homematic-raspi user.err monit[1832]: 'HMIPServer' service restarted 1 times within 1 cycles(s) - exec
Nov 14 11:07:21 homematic-raspi user.info monit[1832]: 'HMIPServer' exec: '/bin/triggerAlarm.tcl HMIPServer restarted WatchDog: hmipserver-restart true'
Nov 14 11:07:21 homematic-raspi user.info monit[1832]: 'HMIPServer' process is running after previous exec error (slow starting or manually recovered?)
Nov 14 11:07:21 homematic-raspi user.info monit[1832]: 'HMIPServer' process is running after previous restart timeout (manually recovered?)
Nov 14 11:07:21 homematic-raspi user.err monit[1832]: 'HMIPServer' failed protocol test [DEFAULT] at [localhost]:39292 [TCP/IP] -- Connection refused
Nov 14 11:07:21 homematic-raspi user.info monit[1832]: 'HMIPServer' trying to restart
Nov 14 11:07:21 homematic-raspi user.info monit[1832]: 'HMIPServer' restart: '/etc/init.d/S62HMServer restart'
```

hmserver.log:
```
2022-11-14 11:07:42,336 de.eq3.cbcs.server.core.vertx.KeyServerWorker ERROR [vert.x-worker-thread-2] Missing key server configuration parameter (Network.Key) for  mode: KEYSERVER_LOCAL 
2022-11-14 11:07:46,424 de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization ERROR [vert.x-eventloop-thread-6] Error 'LOCAL_ADAPTER_NO_SUCH_PORT' while trying to open port '/dev/mmd_hmip': 
de.eq3.cbcs.lib.commdevice.CommDeviceException: Exception while trying to open serial port. Check configured port '/dev/mmd_hmip'
	at de.eq3.cbcs.lib.nrjavaserialdevice.SerialCommDevice.open(SerialCommDevice.java:103) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.lib.hmiptrxcommadapter.HomeMaticIPTRXCommAdapter.open(HomeMaticIPTRXCommAdapter.java:894) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.lib.hmiptrxcommadapter.HomeMaticIPTRXCommAdapter.<init>(HomeMaticIPTRXCommAdapter.java:103) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.server.local.base.internal.ShareableHomeMaticIPTRXCommAdapter.<init>(ShareableHomeMaticIPTRXCommAdapter.java:34) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.server.local.base.internal.LocalServerAdapterInitialization.start(LocalServerAdapterInitialization.java:109) ~[HMIPServer.jar:?]
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[HMIPServer.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[HMIPServer.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_345]
Caused by: gnu.io.NoSuchPortException
	at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:274) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.
```

dmesg:
```
[1932279.648785] eq3loop: eq3loop_write_master() mmd_hmip: not enough space in buffers. free space = 8, required space = 42
[1932279.648823] eq3loop: eq3loop_write_master() return error: -14
```
```


### Additional information

_No response_

**Comment by jens-maus** [comment]
Sorry, but this is not a bug but a local installation/setup issue. See the `Error 'LOCAL_ADAPTER_NO_SUCH_PORT' while trying to open port '/dev/mmd_hmip'` messages. These look like your RF module is not properly identified/setup and thus `multimacd` not being able to setup this `/dev/mmd_hmip` device. Thus, no bug in RaspberryMatic, but a general issue on your end. Look at `/var/log/boot.log` to identify the root cause.

**Comment by RoadRunnr** [comment]
Sorry, this might be a "local configuration problem", but it is defenetly cause by RaspberryMatic and not by some user error.

The setup used to work perfectly fine until it was upgraded to the latest version. So either the upgrade messed up the configuration or something is wrong with the latest version.

In either case, it is not something that was caused by changing or applying a wrong configuration.
