### ISSUE TITLE
Problem with creating group

### ISSUE THREAD

**Issue by Jacuo** [jens-maus/RaspberryMatic#2076]
### Describe the issue you are experiencing

When I try to create new group with one HmIP-eTRV-B thermostat I see message 
"Saving group...Please wait. The direct device connections are being configured. "  forever
In fact after some time group is created, but without  Virtual device, and it is not possible to use set or operate actions

### Describe the behavior you expected

Creating group without problems

### Steps to reproduce the issue

1. Click "create group"
2. Add  HmIP-eTRV-B
3. Click OK
4
...

### What is the version this bug report is based on?

3.65.8.20220831 

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
022-11-27 13:09:13,720 io.vertx.core.impl.ContextImpl ERROR [vert.x-eventloop-thread-0] Unhandled exception 
java.lang.NullPointerException: null
        at de.eq3.ccu.server.internal.RouteHandler$RequestHandler$1.handle(RouteHandler.java:146) ~[HMIPServer.jar:?]
        at de.eq3.ccu.server.internal.RouteHandler$RequestHandler$1.handle(RouteHandler.java:143) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23) ~[HMIPServer.jar:?]
        at io.vertx.core.Promise.fail(Promise.java:89) ~[HMIPServer.jar:?]
        at io.vertx.core.eventbus.impl.ReplyHandler.doFail(ReplyHandler.java:67) ~[HMIPServer.jar:?]
        at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:76) ~[HMIPServer.jar:?]
        at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:24) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:952) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:919) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:942) ~[HMIPServer.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[HMIPServer.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[HMIPServer.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[HMIPServer.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[HMIPServer.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[HMIPServer.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[HMIPServer.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[HMIPServer.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_345]
2022-11-27 13:09:43,083 io.vertx.core.impl.ContextImpl ERROR [vert.x-eventloop-thread-0] Unhandled exception 
java.lang.NullPointerException: null
        at de.eq3.ccu.server.internal.RouteHandler$RequestHandler$1.handle(RouteHandler.java:146) ~[HMIPServer.jar:?]
        at de.eq3.ccu.server.internal.RouteHandler$RequestHandler$1.handle(RouteHandler.java:143) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23) ~[HMIPServer.jar:?]
        at io.vertx.core.Promise.fail(Promise.java:89) ~[HMIPServer.jar:?]
        at io.vertx.core.eventbus.impl.ReplyHandler.doFail(ReplyHandler.java:67) ~[HMIPServer.jar:?]
        at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:76) ~[HMIPServer.jar:?]
        at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:24) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:952) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:919) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53) ~[HMIPServer.jar:?]
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:942) ~[HMIPServer.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[HMIPServer.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[HMIPServer.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[HMIPServer.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[HMIPServer.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[HMIPServer.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[HMIPServer.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[HMIPServer.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_345]
2022-11-27 13:10:05,750 de.eq3.lib.groupadministration.GroupAdministrationService ERROR [vert.x-worker-thread-18] Error in propagateNewGroup
```

### Additional information

Maybe connected with https://github.com/jens-maus/RaspberryMatic/issues/2075

**Comment by Jacuo** [comment]
Any information ?

**Comment by davelosert** [comment]
I am seeing this issue as well. I can not currently add devices to a group. To give a bit more of my logs>

```
2022-12-20 10:53:50,262 de.eq3.lib.groupadministration.GroupAdministrationService ERROR [vert.x-worker-thread-0] Error in propagateNewGroup 
de.eq3.cbcs.legacy.communication.rpc.RpcRemoteException: Error requesting method setReadyConfig: <class 'Exception'>:method "setReadyConfig" is not supported Code: 1
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:155) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
	at com.sun.proxy.$Proxy42.setReadyConfig(Unknown Source) ~[?:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega.createVirtualDevice(VirtualDeviceHandlerRega.java:279) ~[HMIPServer.jar:?]
	at de.eq3.ccu.groupdevice.hmip.service.HmIPGroupDeviceHandler.propagateNewGroup(HmIPGroupDeviceHandler.java:101) ~[HMIPServer.jar:?]
	at de.eq3.lib.groupadministration.GroupAdministrationService.propagateNewGroup(GroupAdministrationService.java:183) ~[HMIPServer.jar:?]
	at de.eq3.lib.groupadministration.GroupAdministrationService.createGroup(GroupAdministrationService.java:154) ~[HMIPServer.jar:?]
	at de.eq3.ccu.groupadministration.http.service.GroupAdministrationController.save(GroupAdministrationController.java:131) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.GroupRequestWorker.handle(GroupRequestWorker.java:46) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.GroupRequestWorker.handle(GroupRequestWorker.java:10) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_352]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
2022-12-20 10:53:50,277 io.vertx.core.impl.ContextImpl ERROR [vert.x-worker-thread-0] Unhandled exception 
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 17
	at com.google.gson.Gson.fromJson(Gson.java:818) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[HMIPServer.jar:?]
	at de.eq3.ccu.groupadministration.http.service.GroupAdministrationController.save(GroupAdministrationController.java:144) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.GroupRequestWorker.handle(GroupRequestWorker.java:46) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.GroupRequestWorker.handle(GroupRequestWorker.java:10) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_352]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 17
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[HMIPServer.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:465) ~[HMIPServer.jar:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[HMIPServer.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80) ~[HMIPServer.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[HMIPServer.jar:?]
	... 14 more
2022-12-20 10:54:19,953 io.vertx.core.impl.ContextImpl ERROR [vert.x-eventloop-thread-0] Unhandled exception 
java.lang.NullPointerException: null
	at de.eq3.ccu.server.internal.RouteHandler$RequestHandler$1.handle(RouteHandler.java:146) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.RouteHandler$RequestHandler$1.handle(RouteHandler.java:143) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23) ~[HMIPServer.jar:?]
	at io.vertx.core.Promise.fail(Promise.java:89) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.ReplyHandler.doFail(ReplyHandler.java:67) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:76) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:24) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:952) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:919) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:942) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[HMIPServer.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[HMIPServer.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
```

According to the second exception, it might be a malformed JSON?

**Comment by Razor144** [comment]
## Issue

I'm also seeing this issue while trying to create a new group, with 1 device or more.

- HmIP-eTRV-B-2
- HmIP-BWTH 

## Setup

- Unraid
- Homeassistant OS
- Rasberrymatic Version: 3.65.11.20221218
- Radio Module: HmIP-RFUSB 4.4.18

## My Logs:

```
2022-12-20 18:34:21,867 io.vertx.core.impl.ContextImpl ERROR [vert.x-worker-thread-19] Unhandled exception 
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 17
	at com.google.gson.Gson.fromJson(Gson.java:818) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:717) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:689) ~[HMIPServer.jar:?]
	at de.eq3.ccu.groupadministration.http.service.GroupAdministrationController.save(GroupAdministrationController.java:144) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.GroupRequestWorker.handle(GroupRequestWorker.java:46) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.GroupRequestWorker.handle(GroupRequestWorker.java:10) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_352]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 17
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[HMIPServer.jar:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:465) ~[HMIPServer.jar:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[HMIPServer.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:80) ~[HMIPServer.jar:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60) ~[HMIPServer.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[HMIPServer.jar:?]
	... 14 more
2022-12-20 18:34:51,849 io.vertx.core.impl.ContextImpl ERROR [vert.x-eventloop-thread-0] Unhandled exception 
java.lang.NullPointerException: null
	at de.eq3.ccu.server.internal.RouteHandler$RequestHandler$1.handle(RouteHandler.java:146) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.RouteHandler$RequestHandler$1.handle(RouteHandler.java:143) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:75) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:230) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23) ~[HMIPServer.jar:?]
	at io.vertx.core.Promise.fail(Promise.java:89) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.ReplyHandler.doFail(ReplyHandler.java:67) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:76) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.ReplyHandler.handle(ReplyHandler.java:24) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:952) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:919) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:942) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[HMIPServer.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[HMIPServer.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
2022-12-20 18:38:53,239 de.eq3.ccu.system.http.service.EnergyPriceController ERROR [vert.x-worker-thread-19] Can´t read the config file for the energy counter: /etc/config/energyPrice (No such file or directory)

**Comment by jens-maus** [comment]
@davelosert @Razor144 
Your issue (looking at the backtrace) looks substantially different than the one of the original author here (@Jacuo). Your issues will most likely be related to #2105 which is a regression in the latest 3.65.11.20221218 version. Downgrade to the previous version or use a nightly snapshot should solve your issues for a moment.

**Comment by davelosert** [comment]
@jens-maus : You might be right! Thank you very much for the quick answer here - and for this awesome project!

**Comment by ScumbagSteve** [comment]
I have the same problem. I wanted to add a widow sensor to an existing group and noticed it's not working.
I tried deleting the group and now I ended up with the situation that I can't add it back (even not with only the "old" existing devices).
Tried to update to newest version, but issue still exists.

**Comment by fmalcher** [comment]
Same here! I can also confirm that the problem appeared for me with 3.65.11.20221218. I then rolled back to 3.65.11.20221005 and it was possible again to create/edit groups.

**Comment by egonkab** [comment]
Same here! Downgrade to 3.65.11.20221005. Greetings from Chemnitz.

**Comment by TheGreyDiamond** [comment]
Is there already a fix done and just not released or is this still open? I spent half a day trying to fix my setup until I saw this issue...

**Comment by jens-maus** [comment]
This issue is already solved in the latest nightly builds, thus will be solved with the next upcoming official release. Until the release happens switch either to a nightly build or downgrade to the previous release.
