### ISSUE TITLE
 Error requesting method listDevices when registering an external XML-RPC Server

### ISSUE THREAD

**Issue by neffmartin** [jens-maus/RaspberryMatic#2272]
### Describe the issue you are experiencing

When registering an external XML-RPC Server (using INIT Method)  the CCU should respond with a list Devices.
This doesn't happen, but instead in the log File it appears an error: 
Error requesting method listDevices: <class 'TypeError'>:MyServer.listDevices() takes 1 positional argument but 2 were given Code: 1
An external triggerd "listDevices()" respondes with the expected behaviour.

### Describe the behavior you expected

When registering an external XML-RPC Server (using INIT Method)  the CCU should respond with a list Devices.
This doesn't happen, but instead in the log File it appears an error: 
Error requesting method listDevices: <class 'TypeError'>:MyServer.listDevices() takes 1 positional argument but 2 were given Code: 1
An external triggerd "listDevices()" respondes with the expected behaviour.

### Steps to reproduce the issue

1. Start an external XML-RPC Server 
2. Register this server using the INIT Method
3.
...

### What is the version this bug report is based on?

3.67.10.20230114

### Which base platform are you running?

oci (Open Container Infrastructure)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
2023-03-30 15:54:01,898 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler DEBUG [test12_WorkerPool-0] Deployed LegacyBackendNotificationHandler for interfaceId test12 
2023-03-30 15:54:01,899 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler INFO  [test12_WorkerPool-0] init finished 
2023-03-30 15:54:01,899 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer INFO  [vert.x-worker-thread-0] Added InterfaceId: test12 
2023-03-30 15:54:01,900 de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil TRACE [vert.x-worker-thread-0] before listDevices 
2023-03-30 15:54:01,900 de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient TRACE [vert.x-worker-thread-0] Call test12 with listDevices 
2023-03-30 15:54:01,909 de.eq3.cbcs.legacy.bidcos.rpc.LegacyServiceHandler TRACE [vert.x-worker-thread-3] RPCMethod: listDevices called 
2023-03-30 15:54:01,920 de.eq3.cbcs.legacy.bidcos.rpc.internal.VirtualRemoteControl DEBUG [vert.x-worker-thread-3] isMigrationPerformedDuringRuntime(): false 
2023-03-30 15:54:01,920 de.eq3.cbcs.legacy.bidcos.rpc.internal.VirtualRemoteControl TRACE [vert.x-worker-thread-3] getChannelDescriptions() 
2023-03-30 15:54:01,924 io.vertx.core.impl.ContextImpl ERROR [vert.x-worker-thread-0] Unhandled exception 
de.eq3.cbcs.legacy.communication.rpc.RpcRemoteException: Error requesting method listDevices: <class 'TypeError'>:MyServer.listDevices() takes 1 positional argument but 2 were given Code: 1
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:155) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
	at com.sun.proxy.$Proxy41.listDevices(Unknown Source) ~[?:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.listDevices(LegacyBackendClient.java:139) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.synchronizedBackendDevices(DeviceUtil.java:156) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:112) ~[HMIPServer.jar:?]
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:26) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_352]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_352]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352]
```

**Comment by jens-maus** [comment]
Please provide the full payload of your application trying to register your XMLRPC server to the HMIPServer.

**Comment by jens-maus** [comment]
Sorry, but please no email reply to github emails. Use the web browser to edit/add comments and don't answer via email to github emails because all your things end up unformatted in the ticket.

**Comment by jens-maus** [comment]
Sorry, but perhaps you should have a look for other python related projects communicating via XMLRPC to a CCU/RaspberryMatic device like https://github.com/danielperna84/pydevccu from @danielperna84 since this can't be a general issue/bug within RaspberryMatic what you are describing here. And this here isn't a discussion fora where you seek for help in your development but only for reporting issues/bugs that need to be fixed in RaspberryMatic itself.

However, if you want I can move over this ticket/issue to the discussion section and then other ppl could help you accordingly.

**Comment by neffmartin** [comment]
Hi Jens,

thanks for your time and looking into. 
I will try the suggestion using daniels approach.
