### ISSUE TITLE
Homematic restore erzeugt Probleme mit Jalousien in Home Assistant

### ISSUE THREAD

**Issue by Norm71** [jens-maus/RaspberryMatic#2382]
### Describe the issue you are experiencing

Da ich auf der RaspberryMatic fehlrehafte Blocks auf der Disk angezeigt bekam habe ich eine neue SD Karte bespielt und das Backup von letzem Monat restored. 
Auf der Raspberrymatic funktioniert auch alles. Doch in HomeAssistant sind alle Jalousien nun mit Problemen zu betreiben.
Nach einem Neustart von HA geht erstmal alles. Dann nach ca.5-7 Schaltvorgängen bei den Jalousien kommt der Fehler: invalid literal for int() with base 10: ‘’

### Describe the behavior you expected

Da RaspberryMatic ja restored wird sollte sich keine Änderung ergeben die zu Problemen bei HA führt.

### Steps to reproduce the issue

1. Connect RM to HA
2. Backup RM
3. Flash Image to new SD Card
4. Restore the Backup
5. Restart HA
6. See if Covers (HmIP-FROLL) working

### What is the version this bug report is based on?

3.69.7.20230626

### Which base platform are you running?

rpi4 (RaspberryPi4)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
Hier ist mal das Log aus HA.

Logger: homeassistant.components.websocket_api.http.connection
Source: components/homematic/cover.py:51
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 18:24:16 (14 occurrences)
Last logged: 18:59:15

[547312526864] invalid literal for int() with base 10: ‘’
[547046173200] invalid literal for int() with base 10: ‘’
[547013812176] invalid literal for int() with base 10: ‘’
Traceback (most recent call last): File “/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py”, line 205, in handle_call_service await hass.services.async_call( File “/usr/src/homeassistant/homeassistant/core.py”, line 1965, in async_call response_data = await coro ^^^^^^^^^^ File “/usr/src/homeassistant/homeassistant/core.py”, line 2005, in _execute_service return await cast( ^^^^^^^^^^^ File “/usr/src/homeassistant/homeassistant/helpers/entity_component.py”, line 235, in handle_service return await service.entity_service_call( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File “/usr/src/homeassistant/homeassistant/helpers/service.py”, line 806, in entity_service_call entity.supported_features is None ^^^^^^^^^^^^^^^^^^^^^^^^^ File “/usr/src/homeassistant/homeassistant/components/cover/init.py”, line 303, in supported_features if self.current_cover_position is not None: ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File “/usr/src/homeassistant/homeassistant/components/homematic/cover.py”, line 51, in current_cover_position return int(self._hm_get_state() * 100) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ValueError: invalid literal for int() with base 10: ‘’

Logger: homeassistant
Source: components/homematic/cover.py:51
First occurred: 18:23:32 (3 occurrences)
Last logged: 18:24:04
```

**Comment by Norm71** [comment]
Found the following Log regarding that issue:
2023-08-12 22:34:29.411 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Entity.async_write_ha_state()
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 808, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 752, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 273, in state
    if (closed := self.is_closed) is None:
                  ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/homematic/cover.py", line 64, in is_closed
    if self.current_cover_position is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/homematic/cover.py", line 51, in current_cover_position
    return int(self._hm_get_state() * 100)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
