### ISSUE TITLE
Python TypeError when starting HomeAssiatant Hub

### ISSUE THREAD

**Issue by MSoegtrop** [jens-maus/RaspberryMatic#2656]
### Describe the issue you are experiencing

Since the update to version `3.73.9.20240130` the Homeassistant Hub does not start any more. In the logs I see this error:
```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
ComponentProtocol, importlib.import_module(self.pkg_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 994, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/config/custom_components/homematicip_local/__init__.py", line 21, in <module>
from .control_unit import ControlConfig, get_storage_folder
File "/config/custom_components/homematicip_local/control_unit.py", line 87, in <module>
from .support import (
File "/config/custom_components/homematicip_local/support.py", line 132, in <module>
class HmBinarySensorEntityDescription(HmEntityDescription, BinarySensorEntityDescription):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
2024-02-17 10:36:31.597 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'homematicip_local': Unable to import component: Exception importing custom_components.homematicip_local
```

### Describe the behavior you expected

HomeAssistant Hub starts normally

### Steps to reproduce the issue

Install latest version of RaspberryMatic on HomeAssistant and reboot

### What is the version this bug report is based on?

3.73.9.20240130

### Which base platform are you running?

rpi3 (RaspberryPi3)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
RaspberryMatic itself boots fine and works fine. The log is:

Mounting /data as /usr/local (Home Assistant Add-On): OK
Starting watchdog...
Identifying host system: Raspberry Pi 3 Model B Rev 1.2 (oci), OK
Initializing RTC Clock: rx8130, OK
Running sysctl: OK
Checking for Factory Reset: not required
Checking for Backup Restore: not required
Running seedrng: OK
Initializing System: OK
Setup ca-certificates: OK
Starting logging: OK
Init onboard LEDs: init, OK
Starting irqbalance: OK
Starting iptables: OK
Starting network: eth0: link up, fixed, firewall, inet up, 172.30.33.0, OK
Identifying Homematic RF-Hardware: ....HmRF: RPI-RF-MOD/GPIO@3f201000.serial, HmIP: RPI-RF-MOD/GPIO@3f201000.serial, OK
Updating Homematic RF-Hardware: RPI-RF-MOD: 4.4.22, not necessary, OK
Starting hs485dLoader: disabled
Starting xinetd: OK
Starting eq3configd: OK
Starting lighttpd: OK
Starting ser2net: disabled
Starting ssdpd: OK
Starting ha-proxy: OK
Starting NUT services: disabled
Initializing Third-Party Addons: OK
Starting LGWFirmwareUpdate: ...OK
Setting LAN Gateway keys: OK
Starting hs485d: disabled
Starting multimacd: .......OK
Starting rfd: ..OK
Starting HMIPServer: .....................OK
Starting ReGaHss: .OK
Starting CloudMatic: disabled
Starting Third-Party Addons: OK
Starting crond: OK
Setup onboard LEDs: booted, OK
Finished Boot: 3.73.9.20240130 (raspmatic_oci_arm64)
```

### Additional information

This did work in the previous version I had installed - I update regularly but can't guarantee I didn't miss one, but it is unlikely that I don't install an update within 2 weeks.

**Comment by MSoegtrop** [comment]
Digging a bit into this, I guess this is the wrong project, I should report at https://github.com/danielperna84/hahomematic.

I leave this open for you to close for information.

**Comment by MSoegtrop** [comment]
Note: Updating hahomematic via HACS to version 1.56 fixed the issue.
