### ISSUE TITLE
HomeaticIp local startet aber ist nicht verfügbar

### ISSUE THREAD

**Issue by fastbag** [jens-maus/RaspberryMatic#2776]
### Describe the issue you are experiencing

Nach einem Update geht plötzlich nichts mehr unter HomeAssistant. Habe schon getestet das Addon zurück zu setzten usw. keine Änderung. kann mich im Addon aber ganz normal einloggen und alles steuern, nur nicht mit HomeAssistant .
Gruß Sven
![image](https://github.com/jens-maus/RaspberryMatic/assets/46375317/ec137288-768e-414f-9b65-75308039f025)

### Describe the behavior you expected

Logger: homeassistant.setup
Quelle: setup.py:320
Erstmals aufgetreten: 14:58:09 (1 Vorkommnisse)
Zuletzt protokolliert: 14:58:09

Setup failed for custom integration 'homematicip_local': Unable to import component: No module named 'custom_components.homematicip_local.const'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 320, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1012, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 992, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1052, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 131, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 16, in <module>
    from .const import (
ModuleNotFoundError: No module named 'custom_components.homematicip_local.const'

### Steps to reproduce the issue

1.
2.
3.
...

### What is the version this bug report is based on?

1.62.1

### Which base platform are you running?

ha-addon (HomeAssistant Add-on)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.setup
Quelle: setup.py:320
Erstmals aufgetreten: 14:58:09 (1 Vorkommnisse)
Zuletzt protokolliert: 14:58:09

Setup failed for custom integration 'homematicip_local': Unable to import component: No module named 'custom_components.homematicip_local.const'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 320, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1012, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 992, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1052, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 131, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/homematicip_local/__init__.py", line 16, in <module>
    from .const import (
ModuleNotFoundError: No module named 'custom_components.homematicip_local.const'
```

**Comment by Baxxy13** [comment]
Tut mir Leid das zu sagen, aber mit dem Ticket bist du hier falsch.
Hier geht's um RaspberryMatic während du ein Problem mit der Custom-Integration 'Homematic(IP) Local' hast.
Das Ticket wäre hier: https://github.com/danielperna84/hahomematic/issues besser platziert.

Vielleicht reicht es ja schon wenn du per HACS auf die letzte Version (1.63.0) aktualisierst und danach deinen HA komplett neu startest.
