### ISSUE TITLE
HMIP-PS: auto-modus can not be set

### ISSUE THREAD

**Issue by rg-engineering** [jens-maus/RaspberryMatic#2945]
### Describe the issue you are experiencing

I try to enable "auto-modus" on HMIP-PS:
![grafik](https://github.com/user-attachments/assets/5d25d36d-bc61-4fef-9d0a-35674d6ac588)

but it does not work. Nothing happens at all.

In log:

```
> 
> 2024-12-02 21:00:48,017 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer ERROR [vert.x-worker-thread-2] IO Exception: Could not add interface: nanopineo3:hm-rpc.0:0d0ec322decb8928ce4de61d64c72759 
> de.eq3.cbcs.legacy.communication.rpc.RpcIOException: org.apache.http.client.ClientProtocolException
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:110) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
> 	at com.sun.proxy.$Proxy38.listDevices(Unknown Source) ~[?:?]
> 	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.listDevices(LegacyBackendClient.java:139) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.synchronizedBackendDevices(DeviceUtil.java:163) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:112) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:26) ~[HMIPServer.jar:?]
> 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
> 	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
> 	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
> 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
> 	at java.lang.Thread.run(Unknown Source) ~[?:?]
> Caused by: org.apache.http.client.ClientProtocolException
> 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:888) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:106) ~[HMIPServer.jar:?]
> 	... 15 more
> Caused by: org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
> 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:232) ~[HMIPServer.jar:?]
> 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[HMIPServer.jar:?]
> 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:686) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:488) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:106) ~[HMIPServer.jar:?]
> 	... 15 more
> 2024-12-02 21:04:18,069 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer ERROR [vert.x-worker-thread-1] IO Exception: Could not add interface: nanopineo3:hm-rpc.0:0d0ec322decb8928ce4de61d64c72759 
> de.eq3.cbcs.legacy.communication.rpc.RpcIOException: org.apache.http.client.ClientProtocolException
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:110) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
> 	at com.sun.proxy.$Proxy38.listDevices(Unknown Source) ~[?:?]
> 	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.listDevices(LegacyBackendClient.java:139) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.synchronizedBackendDevices(DeviceUtil.java:163) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:112) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:26) ~[HMIPServer.jar:?]
> 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
> 	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
> 	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
> 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
> 	at java.lang.Thread.run(Unknown Source) ~[?:?]
> Caused by: org.apache.http.client.ClientProtocolException
> 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:888) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:106) ~[HMIPServer.jar:?]
> 	... 15 more
> Caused by: org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
> 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:232) ~[HMIPServer.jar:?]
> 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[HMIPServer.jar:?]
> 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:686) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:488) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:106) ~[HMIPServer.jar:?]
> 	... 15 more
> 2024-12-02 21:07:48,122 de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer ERROR [vert.x-worker-thread-0] IO Exception: Could not add interface: nanopineo3:hm-rpc.0:0d0ec322decb8928ce4de61d64c72759 
> de.eq3.cbcs.legacy.communication.rpc.RpcIOException: org.apache.http.client.ClientProtocolException
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:110) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82) ~[HMIPServer.jar:?]
> 	at com.sun.proxy.$Proxy38.listDevices(Unknown Source) ~[?:?]
> 	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.listDevices(LegacyBackendClient.java:139) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.synchronizedBackendDevices(DeviceUtil.java:163) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:112) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.bidcos.rpc.internal.InterfaceInitializer.handle(InterfaceInitializer.java:26) ~[HMIPServer.jar:?]
> 	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[HMIPServer.jar:?]
> 	at io.vertx.core.impl.WorkerContext.lambda$emit$0(WorkerContext.java:59) ~[HMIPServer.jar:?]
> 	at io.vertx.core.impl.WorkerContext.lambda$execute$2(WorkerContext.java:104) ~[HMIPServer.jar:?]
> 	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[HMIPServer.jar:?]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
> 	at java.lang.Thread.run(Unknown Source) ~[?:?]
> Caused by: org.apache.http.client.ClientProtocolException
> 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:888) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:106) ~[HMIPServer.jar:?]
> 	... 15 more
> Caused by: org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
> 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:151) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:232) ~[HMIPServer.jar:?]
> 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[HMIPServer.jar:?]
> 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:686) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:488) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[HMIPServer.jar:?]
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[HMIPServer.jar:?]
> 	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:106) ~[HMIPServer.jar:?]
> 	... 15 more
> 
```

### Describe the behavior you expected

auto-modus should be possible to be activiated...

### Steps to reproduce the issue

1. "Wochenprogramm" configured
2. tried to activate "auto-modus"
3.
...

### What is the version this bug report is based on?

3.79.6.20241122

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

RPI-RF-MOD

### Anything in the logs that might be useful for us?

```txt
see above
```

**Comment by jens-maus** [comment]
Geht doch:

![Dec-02-2024 21-40-27](https://github.com/user-attachments/assets/1ad8cdc3-cd9b-4a6f-a68a-d42df7f63287)

Muss also ne Fehlbedienung sein. Auch steht in den Logfiles etwas von `Could not add interface: nanopineo3:hm-rpc.0:0d0ec322decb8928ce4de61d64...` Hat also mit dem gezeigten problem nix zu tun, denn das mit `hm-rpc.0` liest sich nach ioBroker.
