### ISSUE TITLE
Unable to Create/Operate/Delete HmIP-Heating Groups

### ISSUE THREAD

**Issue by jwacalex** [jens-maus/RaspberryMatic#2955]
### Describe the issue you are experiencing

When creating or operating a group, the settings are not transferred to the device. Furthermore, the service message "Device communication disturbed" arises for the group and all affected devices. 

When creating the group without any devices, the same message appears.

When deleting a group, an Exception appears in the logs.

### Describe the behavior you expected

The group should be created and configured

### Steps to reproduce the issue

1. Open Settings -> Group 
2. Create a group
3. Watch for issues in the hm-log
...

### What is the version this bug report is based on?

3.79.6.20241122

### Which base platform are you running?

rpi3 (RaspberryPi3, ARM64/aarch64)

### Which HomeMatic/homematicIP radio module are you using?

HmIP-RFUSB

### Anything in the logs that might be useful for us?

```txt
io.vertx.core.impl.BlockedThreadChecker WARN  [vertx-blocked-thread-checker] Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 5995 ms, time limit is 2000 ms 
io.vertx.core.VertxException: Thread blocked
	at jdk.internal.misc.Unsafe.park(Native Method) ~[?:?]
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source) ~[?:?]
	at java.util.concurrent.LinkedBlockingQueue.poll(Unknown Source) ~[?:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega.registerCallback(VirtualDeviceHandlerRega.java:99) ~[HMIPServer.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.AnnotationAwareRpcHandler.execute(AnnotationAwareRpcHandler.java:80) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:70) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:24) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:187) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:162) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:127) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration$$Lambda$152/0x0000000100317440.run(Unknown Source) ~[?:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:111) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:103) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:193) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:178) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:54) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration$$Lambda$151/0x0000000100317c40.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[HMIPServer.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[HMIPServer.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
2024-12-14 05:32:58,712 io.vertx.core.impl.BlockedThreadChecker WARN  [vertx-blocked-thread-checker] Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 6995 ms, time limit is 2000 ms 
io.vertx.core.VertxException: Thread blocked
	at jdk.internal.misc.Unsafe.park(Native Method) ~[?:?]
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source) ~[?:?]
	at java.util.concurrent.LinkedBlockingQueue.poll(Unknown Source) ~[?:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega.registerCallback(VirtualDeviceHandlerRega.java:99) ~[HMIPServer.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.AnnotationAwareRpcHandler.execute(AnnotationAwareRpcHandler.java:80) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:70) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:24) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:187) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:162) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:127) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration$$Lambda$152/0x0000000100317440.run(Unknown Source) ~[?:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:111) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:103) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:193) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:178) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:54) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration$$Lambda$151/0x0000000100317c40.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[HMIPServer.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[HMIPServer.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
2024-12-14 05:32:59,713 io.vertx.core.impl.BlockedThreadChecker WARN  [vertx-blocked-thread-checker] Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 7995 ms, time limit is 2000 ms 
io.vertx.core.VertxException: Thread blocked
	at jdk.internal.misc.Unsafe.park(Native Method) ~[?:?]
	at java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source) ~[?:?]
	at java.util.concurrent.LinkedBlockingQueue.poll(Unknown Source) ~[?:?]
	at de.eq3.ccu.virtualdevice.service.internal.rega.VirtualDeviceHandlerRega.registerCallback(VirtualDeviceHandlerRega.java:99) ~[HMIPServer.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.AnnotationAwareRpcHandler.execute(AnnotationAwareRpcHandler.java:80) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:70) ~[HMIPServer.jar:?]
	at de.eq3.ccu.server.internal.RpcMessageHandler.handle(RpcMessageHandler.java:24) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50) ~[HMIPServer.jar:?]
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:168) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.dispatch(MessageConsumerImpl.java:187) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.next(HandlerRegistration.java:162) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration$InboundDeliveryContext.dispatch(HandlerRegistration.java:127) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration$$Lambda$152/0x0000000100317440.run(Unknown Source) ~[?:?]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:111) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.dispatch(HandlerRegistration.java:103) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.deliver(MessageConsumerImpl.java:193) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.MessageConsumerImpl.doReceive(MessageConsumerImpl.java:178) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$receive$0(HandlerRegistration.java:54) ~[HMIPServer.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration$$Lambda$151/0x0000000100317c40.run(Unknown Source) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[HMIPServer.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[HMIPServer.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[HMIPServer.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[HMIPServer.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

### Additional information

Duty Cycle: 2%
Carrier Sense: 0%

**Comment by Baxxy13** [comment]
Welche Art von Gruppe?
HmIP-Heizungssteuerung oder Heizungssteuerung?

**Comment by jwacalex** [comment]
Group Type: HmIP-Heating control
Group Memebers: 2x HmIP-eTRV-C-2

**Comment by Baxxy13** [comment]
I cannot reproduce this here on a test system.
It is possible to create new IP heating groups here without any problems, whether empty or with integrated devices.

**Comment by jwacalex** [comment]
I'll reopen the issue as soon as I've a reliable way of reproducing it.
