### ISSUE TITLE
Funk und Programm Probleme

### ISSUE THREAD

**Issue by hooker78** [jens-maus/RaspberryMatic#982]
Hallo,

seit dem Update auf die letzte Version für den PI3 kommt es nach ein paar Tagen Betrieb immer zu einem Ausfall der Funkverbindung. Ich kann es leider nicht richtig eingrenzen - es scheint als würde noch Empfangen werden, aber nicht mehr gesendet. Das Log ist dann voll mit solchen Meldungen und es hilft nur ein Restart.

VG Thorsten

`Nov 5 20:48:14 org.apache.http.impl.client.DefaultHttpClient INFO  [HmIP-RF_java_WorkerPool-1] I/O exception (java.net.SocketException) caught when processing request to {}->http://127.0.0.1:39292: Broken pipe (Write failed) 
Nov 5 20:48:14 org.apache.http.impl.client.DefaultHttpClient INFO  [HmIP-RF_java_WorkerPool-1] Retrying request to {}->http://127.0.0.1:39292 
Nov 5 20:48:43 de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler WARN  [vert.x-worker-thread-4] No such device while filtering device parameters on event. 
de.eq3.cbcs.server.core.backend.DeviceNotFoundException
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.getDeviceID(DeviceUtil.java:2956)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.getDevice(DeviceUtil.java:3312)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.getFilterParamsFromNotificationDTO(LegacyNotificationHandler.java:798)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handleReceivedStatusData(LegacyNotificationHandler.java:584)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handleCommonNotification(LegacyNotificationHandler.java:242)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handle(LegacyNotificationHandler.java:215)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handle(LegacyNotificationHandler.java:52)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Nov 5 20:49:07 org.apache.http.impl.client.DefaultHttpClient INFO  [HmIP-RF_java_WorkerPool-1] I/O exception (java.net.SocketException) caught when processing request to {}->http://127.0.0.1:39292: Broken pipe (Write failed) 
Nov 5 20:49:07 org.apache.http.impl.client.DefaultHttpClient INFO  [HmIP-RF_java_WorkerPool-1] Retrying request to {}->http://127.0.0.1:39292 
Nov 5 20:49:47 de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler WARN  [vert.x-worker-thread-4] No such device while filtering device parameters on event. 
de.eq3.cbcs.server.core.backend.DeviceNotFoundException
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.getDeviceID(DeviceUtil.java:2956)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.getDevice(DeviceUtil.java:3312)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.getFilterParamsFromNotificationDTO(LegacyNotificationHandler.java:798)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handleReceivedStatusData(LegacyNotificationHandler.java:584)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handleCommonNotification(LegacyNotificationHandler.java:242)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handle(LegacyNotificationHandler.java:215)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handle(LegacyNotificationHandler.java:52)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Nov 5 20:50:53 de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler WARN  [vert.x-worker-thread-0] No such device while filtering device parameters on event. 
de.eq3.cbcs.server.core.backend.DeviceNotFoundException
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.getDeviceID(DeviceUtil.java:2956)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.getDevice(DeviceUtil.java:3312)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.getFilterParamsFromNotificationDTO(LegacyNotificationHandler.java:798)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handleReceivedStatusData(LegacyNotificationHandler.java:584)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handleCommonNotification(LegacyNotificationHandler.java:242)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handle(LegacyNotificationHandler.java:215)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handle(LegacyNotificationHandler.java:52)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Nov 5 20:51:57 de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler WARN  [vert.x-worker-thread-3] No such device while filtering device parameters on event. 
de.eq3.cbcs.server.core.backend.DeviceNotFoundException
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.getDeviceID(DeviceUtil.java:2956)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.DeviceUtil.getDevice(DeviceUtil.java:3312)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.getFilterParamsFromNotificationDTO(LegacyNotificationHandler.java:798)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handleReceivedStatusData(LegacyNotificationHandler.java:584)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handleCommonNotification(LegacyNotificationHandler.java:242)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handle(LegacyNotificationHandler.java:215)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyNotificationHandler.handle(LegacyNotificationHandler.java:52)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Nov 5 20:52:05 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-6] SYSTEM: 0 Accesspoints in Queue 
Nov 5 20:52:05 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-6] SYSTEM: Permanent-/Burstlistener Handler utilization: 0/50 used 
Nov 5 20:52:05 de.eq3.cbcs.server.core.otau.DeviceBackgroundUpdateSubsystem INFO  [vert.x-eventloop-thread-6] SYSTEM: Eventlistener Handler utilization: 0/50 us`

**Comment by jens-maus** [comment]
Tut mir leid, aber das hier ist kein Supportforum aber ein Bug/Issuetracker, d.h. für Dinge die DEFINITIV ein Bug darstellen oder Funktionserweiterungen.

Bitte an das [HomeMatic Forum](https://homematic-forum.de/) wenden!  Das stand übrigens auch im Ticket Template das du leider komplett ignoriert/gelöscht hast statt es mit ausführlichen technischen Details zu füttern. Auch hilft der von dir beigefügte Logauszug nicht weiter und die dort drin vermerkte Exceptions haben nichts mit den von dir beschriebenen Symptomen zu tun. Ergo, bitte an das HomeMatic Forum wenden für Support.
